# Generated by Django 6.0.5 on 2026-06-04 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_otp_code_profile_otp_expires'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_push',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_key', models.CharField(max_length=120)),
                ('topic_display', models.CharField(blank=True, max_length=160)),
                ('score_type', models.CharField(choices=[('detection', 'detection'), ('confidence', 'confidence'), ('overall', 'overall')], default='detection', max_length=12)),
                ('threshold', models.IntegerField(default=75)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_push', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
