# Generated by Django 6.0.5 on 2026-06-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_notify_email_profile_notify_push_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reset_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
