# Generated by Django 6.0.5 on 2026-06-16 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_gradehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('display', models.CharField(blank=True, max_length=160)),
                ('kind', models.CharField(choices=[('topic', 'topic'), ('market', 'market')], default='topic', max_length=12)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='gradehistory',
            new_name='accounts_gr_user_id_b62fae_idx',
            old_name='accounts_gr_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='gradehistory',
            new_name='accounts_gr_topic_2092a6_idx',
            old_name='accounts_gr_topic_idx',
        ),
        migrations.RenameIndex(
            model_name='gradehistory',
            new_name='accounts_gr_created_435d3b_idx',
            old_name='accounts_gr_created_idx',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.watchlist'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together={('watchlist', 'key')},
        ),
    ]
