# Generated by Django 6.0.5 on 2026-06-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_dashboardlayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardlayout',
            name='favorites',
            field=models.JSONField(default=list),
        ),
    ]
