# Generated by Django 6.0.5 on 2026-06-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_dashboardlayout_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='notify_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='notify_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='notify_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='notify_threshold',
            field=models.IntegerField(default=75),
        ),
    ]
