# Generated by Django 6.0.5 on 2026-06-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alert_notify_sms_profile_notify_sms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('topic', 'topic'), ('market', 'market')], default='topic', max_length=12),
        ),
    ]
